### PR TITLE
Display user metrics

### PR DESCRIPTION
**Pull request by ShanMehr**
display user metrics (PR for demonstration):
we want to view display metrics on frontend

### CODE REVIEW

**Comment by ianmccurry11** [comment]
Besides camelCase lgtm

**Review by natedog0027 — APPROVED** [review]
Looks good. Good use of the MVC system.

**Review by ianmccurry11 — APPROVED** [review]
LGTM

**Review by JMestre32 — APPROVED** [review]
LGTM, nice

**Pull request merged**
